### ISSUE TITLE
Error while installing scout_realtime on OSX

### ISSUE THREAD

**Issue by melz** [scoutapp/scout_realtime#28]
Tried installing on OSX Mountain Lion and received this error:

```
jubilee:~ melz$ gem install scout_realtime
Successfully installed server_metrics-1.2.1
Successfully installed scout_realtime-1.0.1
2 gems installed
Installing ri documentation for server_metrics-1.2.1...
Installing ri documentation for scout_realtime-1.0.1...
Installing RDoc documentation for server_metrics-1.2.1...
Installing RDoc documentation for scout_realtime-1.0.1...
jubilee:~ melz$ scout_realtime
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- json (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /Library/Ruby/Gems/1.8/gems/scout_realtime-1.0.1/lib/scout_realtime.rb:23
    from /Library/Ruby/Gems/1.8/gems/scout_realtime-1.0.1/bin/scout_realtime:4:in `load'
    from /Library/Ruby/Gems/1.8/gems/scout_realtime-1.0.1/bin/scout_realtime:4
    from /usr/bin/scout_realtime:19:in `load'
    from /usr/bin/scout_realtime:19
```

Not a Ruby person so some help would be appreciated. Is this a dependency issue?

Thanks!

**Comment by melz** [comment]
Nevermind. It was a dependency error for the json gem.
Closing issue...
