### ISSUE TITLE
`gem_original_require': no such file to load

### ISSUE THREAD

**Issue by andrewcstewart** [scoutapp/scout_realtime#50]
Hi,

Receiving the following error trying to run: 

```
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- json (LoadError)
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/scout_realtime-1.0.5/lib/scout_realtime.rb:23
    from /usr/lib/ruby/gems/1.8/gems/scout_realtime-1.0.5/bin/scout_realtime:4:in `load'
    from /usr/lib/ruby/gems/1.8/gems/scout_realtime-1.0.5/bin/scout_realtime:4
    from /usr/bin/scout_realtime:19:in `load'
    from /usr/bin/scout_realtime:19
```

**Comment by dlanderson** [comment]
Hi @andrewcstewart - can you try 'gem install json' to see if that fixes it? If not, please post the output of 'gem list'.

**Comment by andrewcstewart** [comment]
Thanks, that worked.  ( ruby newb here)

**Comment by binarycpu** [comment]
I've found a variant, `gem install json -v '1.8.3'` for cases where a specific version is needed
